### ISSUE TITLE
Remote Chaos December 2021

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/Events#1]
Would we like to have some hangouts ( virtual table ), events, games, talks during the conference time? It is the 20 year anniversary of the project as well! 

Add ideas, your availability to make them happen, and lets see what we can put together!

**Comment by marek22k** [comment]
Idk suggestion:
  - Online game server (I think it has already set up Freeciv and Wesnoth servers)
Suggestions from me:
- It seems to be well received or some are currently doing it: Ask Me Anything (AMA). I would certainly be interested to hear how certain people got into I2P. However, there may be privacy concerns about an AMA.

**Comment by Shoalsteed** [comment]
I would like to have a call for participation - but we would need to have the communication architecture and moderation needs in place ahead of that.

**Comment by Shoalsteed** [comment]
I would also like to be able to record the talks as part of the 20 year celebration.

**Comment by marek22k** [comment]
I would say we can close this issue now that rc3 is over.
